### PR TITLE
US77372: Add responsive rules for typography headings 1-4.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by njostonehouse** [comment]
@dbatiste here's a first attempt at making headings responsive.

**Comment by dlockhart** [comment]
Just curious if we're considering decreasing the base font size instead or in addition to this approach? It looks like not all levels are shrinking at the same rate (H1- 75%, H2 - 67%, H3/H4 - 80%), which would make a base font change on its own not enough to get the same effect as this PR.

**Comment by njostonehouse** [comment]
As far as I know, "consideration" is all that's been given to the idea of a modified base font size. I suspect that our phone size headings would get adjusted if something like that ever went through, so these styles would have to get updated (or at least verified) anyway.

**Comment by njostonehouse** [comment]
Just spoke to @dlockhart about this to clarify. Responsively changing the base font size in the LMS might be a really elegant way to get (roughly) this effect for all font sizes. Putting this on hold while I try that out.

**Comment by dbatiste** [comment]
Changing the root size also affects things like some whitespace (which was the original intent - if the text scales down/up, the whitespace changes proportionally).  That may or may not be desired in this case... ??

**Comment by njostonehouse** [comment]
@dbatiste I think so. We're going to give it a shot and review the effects with design and see if they like it. Initially the impression seems to be that they prefer targeting the root approach.

**Comment by njostonehouse** [comment]
A few issues so far with reducing the root font size on mobile:
- We have some icon problems (background icons get cut off when rem height/width shrinks)
- Legibility becomes at (more of an) issue at 14px with our font weight
- interaction targets (eg: menu links) shrink to be less easy to interact with.
These could be a problem with the choice of 14px specifically, or may need us to reconsider our responsive approach to text (again).

**Comment by njostonehouse** [comment]
Looks like the root font size reduction approach isn't super, so we're looking to revive this approach again. I am going to look into the other typography rules though, to make sure that all the text resizes instead of just headings, probably.

**Pull request merged**
